name: arcane-duelists
version: 0.1.0.0
synopsis: Arcane Duelists - shared library, server, and client
category: Games
license: MIT
author: "Arcane Team"
maintainer: "you@example.com"
homepage: "https://example.com/arcane-duelists"
description: |
  Arcane Duelists is a small 2D top-down multiplayer game.
  This package provides a shared library with types and protocol, a server
  executable that manages game state and networking, and a client executable
  that renders the game and connects to the server.
extra-source-files:
  - README.md
build-type: Simple
cabal-version: ">=1.10"

library:
  name: shared-lib
  source-dirs: shared/src
  exposed-modules:
    - GameTypes
    - Protocol
    - Common
    - NetworkTypes
    - Network.Protocol
    - Models
    - DBTypes
    - Account
    - Types.Common
    - Types.Player
    - Types.Enemy
    - Types.Item
  ghc-options: -Wall
  default-language: Haskell2010
  dependencies:
    - base >=4.9 && <5
    - aeson
    - text
    - bytestring
    - containers
    - unordered-containers
    - stm

executables:
  server-exe:
    main: app/Main.hs
    source-dirs: server
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    default-language: Haskell2010
    dependencies:
      - base
      - shared-lib
      - websockets
      - stm
      - aeson
      - text
      - bytestring
      - containers
      - mtl

  client-exe:
    main: ClientMain.hs
    source-dirs: client
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    default-language: Haskell2010
    dependencies:
      - base
      - shared-lib
      - gloss
      - websockets
      - aeson
      - text
      - bytestring
      - mtl